variables:
    IMAGE_NAME: supernova0730/ae86

stages:
    - test
    - build

run_tests:
    stage: test
    image: golang
    script:
        - go test

build_image:
    stage: build
    image: docker:20.10.20
    services:
        - docker:20.10.20-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS 
    script:
        - docker build --tag $IMAGE_NAME .
        - docker push $IMAGE_NAME