variables:
    IMAGE_NAME: supernova0730/ae86
    CONTAINER: ae86

stages:
    - build
    - deploy

build_image:
    stage: build
    image: docker:20.10.20
    services:
        - docker:20.10.20-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS 
    script:
        - docker build --tag $IMAGE_NAME .
        - docker push $IMAGE_NAME

deploy:
    stage: deploy
    before_script:
        - chmod 400 $SSH_KEY
    script:
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $SSH_USER@$SSH_HOST "
            sudo docker rm -f $CONTAINER || true &&
            sudo docker image rm $IMAGE_NAME || true &&
            sudo docker run --name=$CONTAINER -dp 80:8000 
            -e DB_HOST=$DB_HOST 
            -e DB_PORT=$DB_PORT 
            -e DB_USER=$DB_USER 
            -e DB_PASSWORD=$DB_PASSWORD 
            -e DB_NAME=$DB_NAME 
            -e HTTP_HOST=0.0.0.0 
            $IMAGE_NAME --production"




    