variables:
    IMAGE_NAME: supernova0730/ae86

stages:
    - build
    - deploy

build_image:
    stage: build
    image: docker:20.10.20
    services:
        - docker:20.10.20-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS 
    script:
        - docker build --tag $IMAGE_NAME .
        - docker push $IMAGE_NAME

deploy:
    stage: deploy
    before_script:
        - chmod 400 $SSH_KEY
    script:
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@91.201.215.23 "
            echo $USER_PASS sudo -S docker ps -aq | xargs docker stop | xargs docker rm &&  
            echo $USER_PASS sudo -S sudo docker run -dp 80:8000 $IMAGE_NAME" 
            # echo $REGISTRY_PASS | docker login -u $REGISTRY_USER --password-stdin &&




    