variables:
  SERVER_IP: 91.201.215.23
  SERVER_USER: ubuntu

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:20.10.20
  services:
    - docker:20.10.20-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker compose build
    - docker compose push
  only:
    refs:
      - develop

deploy:
  stage: deploy
  # image: docker:20.10.20
  # services:
  #   - docker:20.10.20-dind
  # variables:
  #   DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    # - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - chmod 400 $SSH_KEY
  script:
    # - eval $(ssh-agent -s)
    # - cat "$SSH_KEY" | ssh-add - > /dev/null
    # - docker-compose -H "ssh://$SERVER_USER@$SERVER_IP" down --remove-orphans
    # - docker-compose -H "ssh://$SERVER_USER@$SERVER_IP" pull
    # - docker-compose -H "ssh://$SERVER_USER@$SERVER_IP" up -d
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $SERVER_USER@$SERVER_IP "
        docker compose -f docker-compose.yml down --remove-orphans &&
        docker compose -f docker-compose.yml pull &&
        docker compose -f docker-compose.yml up -d"
  only:
    refs:
      - develop





    